import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Chip } from "@/components/ui/chip";
import type { CaseStudy, Metric as MetricData, Resource, Service, Testimonial as TestimonialData } from "@/types/wordpress";
import styles from "./sections.module.css";
type ServiceCardIcon = "branding" | "development" | "marketing";
export function ServiceCard({service, icon, showLabel=true}:{service?:Service;icon?:ServiceCardIcon;showLabel?:boolean}){if(!service) return null; return <article className={`${styles.card} ${styles.serviceCard}${icon ? ` ${styles.serviceCardWithIcon}` : ""}`}>{showLabel ? <Chip>Servicio</Chip> : null}{icon ? <span className={styles.serviceIcon} aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round">{icon === "branding" ? <><path d="m15 5 4 4"/><path d="M4 20l4.2-1 10.9-10.9a2.1 2.1 0 0 0-3-3L5.2 16 4 20Z"/><path d="m13.5 6.5 4 4"/></> : icon === "development" ? <><path d="m8 6-6 6 6 6"/><path d="m16 6 6 6-6 6"/><path d="m14 4-4 16"/></> : <><path d="M3 3v18h18"/><path d="m7 14 4-4 3 3 6-7"/><path d="M16 6h4v4"/></>}</svg></span> : null}<h3>{service.name}</h3>{service.summary ? <p>{service.summary}</p> : null}</article>}
export function CaseStudyCard({caseStudy,featuredPreview=false,className}:{caseStudy?:CaseStudy;featuredPreview?:boolean;className?:string}){if(!caseStudy) return null; const image=featuredPreview ? caseStudy.gallery[0] : undefined; const displayName=(caseStudy.clientName || caseStudy.title).replace(/\s*[—–-]\s*Demo$/i, ""); return <article className={`${styles.card} ${className ?? ""}`}><Chip>Caso de éxito</Chip><h3>{displayName}</h3>{caseStudy.solution ? <p>{caseStudy.solution}</p> : null}{image ? <Image src={image.url} alt={image.alt || `Vista del proyecto ${displayName}`} width={image.width || 1600} height={image.height || 900} sizes="(max-width: 767px) calc(100vw - 3rem), (max-width: 1100px) 32vw, 24vw" unoptimized/> : null}{featuredPreview ? <Link href={`/casos-de-exito/${caseStudy.slug}`}>Ver caso completo <span aria-hidden="true">→</span></Link> : null}</article>}
export function ResourceCard({resource}:{resource?:Resource}){if(!resource) return null; return <article className={styles.card}><Chip>Recurso</Chip><h3>{resource.title}</h3>{resource.featuredExcerpt || resource.excerpt ? <p>{resource.featuredExcerpt || resource.excerpt}</p> : null}</article>}
export function Metric({metric}:{metric?:MetricData}){if(!metric?.label || !metric.value) return null; return <article className={styles.metric}><strong>{metric.value}</strong><span>{metric.label}</span></article>}
export function Testimonial({testimonial}:{testimonial?:TestimonialData}){if(!testimonial) return null; return <figure className={styles.card}><blockquote>“{testimonial.quote}”</blockquote><figcaption>{[testimonial.personName, testimonial.jobTitle, testimonial.company].filter(Boolean).join(" · ")}</figcaption></figure>}
export function CtaSection({label="Cuéntanos tu proyecto",url="#contacto",contact="",headingAs="h2",eyebrow="Proyecto"}:{label?:string;url?:string;contact?:string;headingAs?:"h1"|"h2"|"h3";eyebrow?:string}){const Heading = headingAs; return <section id="contacto" className={styles.cta}><div>{eyebrow ? <p className={styles.eyebrow}>{eyebrow}</p> : null}<Heading>Conversemos.</Heading>{contact&&<p>{contact}</p>}</div><Button href={url}>{label}</Button></section>}
