"use client";
import { FormEvent, useState } from "react";
import Link from "next/link";
import { Button } from "../ui/button";
import { FeedbackMessage } from "../ui/feedback-message";
import { validateContactPayload, type ContactPayload, type ContactErrors } from "../../lib/contact/validation";
import styles from "./contact-form.module.css";
const initial: ContactPayload = { name:"", company:"", email:"", phone:"", service:"", budget:"", timeline:"", message:"", consent:false, honeypot:"" };
export function ContactForm() {
  const [form, setForm] = useState(initial); const [errors, setErrors] = useState<ContactErrors>({}); const [status, setStatus] = useState<"idle"|"submitting"|"success"|"error">("idle");
  const update = (key: keyof ContactPayload, value: string|boolean) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const validation = validateContactPayload(form); if (!validation.ok) { setErrors(validation.errors); const first = Object.keys(validation.errors)[0]; if (first) document.getElementById(`contact-${first}`)?.focus(); return; } setErrors({}); setStatus("submitting"); try { const response = await fetch("/api/contact", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(validation.data) }); const result = await response.json().catch(()=>({})); if (!response.ok) { setErrors(result.fields ?? {}); setStatus("error"); const first = Object.keys(result.fields ?? {})[0]; if (first) document.getElementById(`contact-${first}`)?.focus(); return; } setForm(initial); setStatus("success"); } catch { setStatus("error"); } };
  const field = (key: keyof ContactPayload, label: string, type = "text", required = false, autoComplete?: string) => <label className={styles.field} htmlFor={`contact-${key}`}><span>{label}{required && " *"}</span><input id={`contact-${key}`} name={key} type={type} value={String(form[key])} required={required} disabled={status === "submitting"} autoComplete={autoComplete} aria-invalid={Boolean(errors[key])} aria-describedby={errors[key] ? `contact-${key}-error` : undefined} onChange={(event)=>update(key,event.target.value)} />{errors[key] && <span id={`contact-${key}-error`} className={styles.error}>{errors[key]}</span>}</label>;
  return <form className={styles.form} onSubmit={submit} noValidate><div className={styles.grid}>{field("name","Nombre","text",true,"name")}{field("company","Empresa","text",false,"organization")}{field("email","Correo","email",true,"email")}{field("phone","Teléfono","tel",false,"tel")}<label className={styles.field} htmlFor="contact-service"><span>Servicio de interés *</span><select id="contact-service" name="service" value={form.service} required disabled={status === "submitting"} aria-invalid={Boolean(errors.service)} aria-describedby={errors.service ? "contact-service-error" : undefined} onChange={(event)=>update("service",event.target.value)}><option value="">Selecciona una opción</option><option>Diseño y Branding</option><option>Desarrollo Web</option><option>Marketing Digital</option></select>{errors.service && <span id="contact-service-error" className={styles.error}>{errors.service}</span>}</label>{field("budget","Presupuesto aproximado","text",false,"off")}{field("timeline","Plazo o fecha estimada","text",false,"off")}</div>{field("message","Mensaje / proyecto","text",true)}<label className={styles.checkbox}><input id="contact-consent" type="checkbox" checked={form.consent} disabled={status === "submitting"} aria-invalid={Boolean(errors.consent)} aria-describedby={errors.consent ? "contact-consent-error" : undefined} onChange={(event)=>update("consent",event.target.checked)} /><span>Acepto el <Link href="/aviso-de-privacidad">aviso de privacidad</Link>.</span></label>{errors.consent && <span id="contact-consent-error" className={styles.error}>{errors.consent}</span>}<label className={styles.honeypot} aria-hidden="true">No completar<input tabIndex={-1} autoComplete="off" value={form.honeypot} onChange={(event)=>update("honeypot",event.target.value)} /></label><div aria-live="polite">{status === "success" && <FeedbackMessage>Solicitud enviada. Te contactaremos con el siguiente paso.</FeedbackMessage>}{status === "error" && <FeedbackMessage type="error">No pudimos enviar la solicitud. Revisa los campos e inténtalo de nuevo.</FeedbackMessage>}</div><Button type="submit" disabled={status === "submitting"} aria-busy={status === "submitting"}>{status === "submitting" ? "Enviando…" : "Enviar solicitud"}</Button></form>;
}
