import type { CallToAction, CaseStudy, GlobalSettings, MediaAsset, Resource, Service, TeamMember, Testimonial } from "../../types/wordpress";

type WordPressPost = { id: number; slug: string; title?: { rendered?: string }; content?: { rendered?: string }; excerpt?: { rendered?: string }; date?: string; featured_media?: number; meta?: Record<string, unknown>; _embedded?: { "wp:featuredmedia"?: Array<{ id: number; source_url?: string; alt_text?: string; media_details?: { width?: number; height?: number } }> } };
const text = (value: unknown): string => typeof value === "string" ? value : "";
const integer = (value: unknown): number => Number.isInteger(value) ? value as number : 0;
const boolean = (value: unknown): boolean => value === true;
const list = (value: unknown): string[] => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
const ids = (value: unknown): number[] => Array.isArray(value) ? value.filter((item): item is number => Number.isInteger(item)) : [];
const cta = (value: unknown): CallToAction => ({ label: text((value as Record<string, unknown>)?.label), url: text((value as Record<string, unknown>)?.url) });
const seo = (value: unknown) => ({ title: text((value as Record<string, unknown>)?.title), description: text((value as Record<string, unknown>)?.description), noindex: boolean((value as Record<string, unknown>)?.noindex) });
export const media = (post: WordPressPost): MediaAsset | undefined => { const item = post._embedded?.["wp:featuredmedia"]?.[0]; return item?.source_url ? { id: item.id, url: item.source_url, alt: item.alt_text ?? "", width: item.media_details?.width, height: item.media_details?.height } : undefined; };
export const service = (post: WordPressPost): Service => ({ id: post.id, slug: post.slug, name: text(post.title?.rendered), summary: text(post.meta?.["3cuartos_summary"]), visualIdentifier: text(post.meta?.["3cuartos_visual_identifier"]), description: text(post.content?.rendered), capabilities: list(post.meta?.["3cuartos_capabilities"]), image: media(post), cta: cta(post.meta?.["3cuartos_cta"]), order: integer(post.meta?.["3cuartos_sort_order"]), seo: seo(post.meta?.["3cuartos_seo"]), isProvisional: boolean(post.meta?.["3cuartos_is_provisional"]) });
export const caseStudy = (post: WordPressPost): CaseStudy => ({ id: post.id, slug: post.slug, title: text(post.title?.rendered), clientName: text(post.meta?.["3cuartos_client_name"]), challenge: text(post.meta?.["3cuartos_challenge"]), solution: text(post.meta?.["3cuartos_solution"]), serviceIds: ids(post.meta?.["3cuartos_service_ids"]), results: list(post.meta?.["3cuartos_results"]), metrics: Array.isArray(post.meta?.["3cuartos_metrics"]) ? post.meta?.["3cuartos_metrics"] as CaseStudy["metrics"] : [], gallery: [], testimonialId: integer(post.meta?.["3cuartos_testimonial_id"]) || undefined, cta: cta(post.meta?.["3cuartos_cta"]), seo: seo(post.meta?.["3cuartos_seo"]), isProvisional: boolean(post.meta?.["3cuartos_is_provisional"]) });
export const testimonial = (post: WordPressPost): Testimonial => ({ id: post.id, quote: text(post.content?.rendered), personName: text(post.meta?.["3cuartos_person_name"]), jobTitle: text(post.meta?.["3cuartos_job_title"]), company: text(post.meta?.["3cuartos_company"]), image: media(post), caseStudyId: integer(post.meta?.["3cuartos_case_study_id"]) || undefined, order: integer(post.meta?.["3cuartos_sort_order"]), isProvisional: boolean(post.meta?.["3cuartos_is_provisional"]) });
export const teamMember = (post: WordPressPost): TeamMember => ({ id: post.id, slug: post.slug, name: text(post.title?.rendered), biography: text(post.content?.rendered), role: text(post.meta?.["3cuartos_role"]), image: media(post), links: Array.isArray(post.meta?.["3cuartos_profile_links"]) ? post.meta?.["3cuartos_profile_links"] as TeamMember["links"] : [], order: integer(post.meta?.["3cuartos_sort_order"]), isProvisional: boolean(post.meta?.["3cuartos_is_provisional"]) });
export const resource = (post: WordPressPost): Resource => ({ id: post.id, slug: post.slug, title: text(post.title?.rendered), excerpt: text(post.excerpt?.rendered), featuredExcerpt: text(post.meta?.["3cuartos_featured_excerpt"]), content: text(post.content?.rendered), image: media(post), cta: cta(post.meta?.["3cuartos_cta"]), readingTime: integer(post.meta?.["3cuartos_reading_time"]), publishedAt: text(post.date) });
export const globalSettings = (value: unknown): GlobalSettings => { const raw = value as Record<string, unknown>; return { brandName: text(raw?.brandName), contact: { publicEmail: text((raw?.contact as Record<string, unknown>)?.publicEmail), phone: text((raw?.contact as Record<string, unknown>)?.phone) }, whatsappUrl: text(raw?.whatsappUrl), bookingUrl: text(raw?.bookingUrl), socialLinks: Array.isArray(raw?.socialLinks) ? raw.socialLinks as GlobalSettings["socialLinks"] : [], legalLinks: Array.isArray(raw?.legalLinks) ? raw.legalLinks as GlobalSettings["legalLinks"] : [], globalCta: cta(raw?.globalCta), defaultSeo: seo(raw?.defaultSeo) }; };
