"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { Button } from "@/components/ui/button";
import type { Service } from "@/types/wordpress";
import { ProblemsSection } from "@/components/sections/problems-section";
import { BrandLogo } from "@/components/ui/brand-logo";
import { ScrollSplitHeading } from "@/components/motion/scroll-split-heading";
import { HomeSystemScene } from "./home-system-scene";
import styles from "./immersive-home.module.css";

const disciplineDetails = [
  { capabilities: ["Identidad", "Concepto", "Comunicación"] },
  { capabilities: ["UX/UI", "Desarrollo", "Automatización"] },
  { capabilities: ["Contenido", "Campañas", "Analítica"] },
];
const projects = [{ name: "Amazonas Fit", category: "Branding e identidad", className: "projectBrand", image: "/images/projects/amazonas-fit-provisional.png", alt: "Amazonas Fit — imagen provisional" }, { name: "Natuo", category: "E-commerce y marca", className: "projectProduct", image: "/images/projects/natuo-provisional.png", alt: "Natuo — imagen provisional" }, { name: "Anonymask Studio", category: "Experiencia digital", className: "projectDigital", image: "/images/projects/anonymask-studio-provisional.png", alt: "Anonymask Studio — imagen provisional" }];

export function ImmersiveHome({ services, ctaLabel, ctaUrl, showProjects = true, heroOnly = false, motionProfile = "default" }: { services: Service[]; ctaLabel: string; ctaUrl: string; showProjects?: boolean; heroOnly?: boolean; motionProfile?: "default" | "about" }) {
  const reduced = useReducedMotion(); const isAboutProfile = motionProfile === "about"; const { scrollYProgress } = useScroll(); const heroScale = useTransform(scrollYProgress, [0, isAboutProfile ? .24 : .14, isAboutProfile ? .46 : .3], [1, reduced || !isAboutProfile ? 1 : .96, reduced || !isAboutProfile ? 1 : .9]); const heroExitX = useTransform(scrollYProgress, [0, isAboutProfile ? .24 : .13, isAboutProfile ? .46 : .3], ["0vw", "0vw", isAboutProfile ? "-7vw" : "-30vw"]); const heroExitY = useTransform(scrollYProgress, [0, isAboutProfile ? .24 : .13, isAboutProfile ? .46 : .3], ["0vh", "0vh", isAboutProfile ? "-7vh" : "-12vh"]); const heroOpacity = useTransform(scrollYProgress, [0, isAboutProfile ? .34 : .18, isAboutProfile ? .46 : .3], [1, 1, isAboutProfile ? .72 : .16]); const orbitalScale = useTransform(scrollYProgress, [0, isAboutProfile ? .24 : .14, isAboutProfile ? .46 : .3], [1, isAboutProfile ? 1.02 : 1.05, isAboutProfile ? 1.15 : 1.38]); const modulesY = useTransform(scrollYProgress, [0, isAboutProfile ? .24 : .14, isAboutProfile ? .46 : .3], ["0vh", "0vh", isAboutProfile ? "10vh" : "18vh"]);
  const titleLineOneX = useTransform(scrollYProgress, [0, isAboutProfile ? .22 : .12, isAboutProfile ? .46 : .3], ["0vw", "0vw", isAboutProfile ? "-16vw" : "0vw"]);
  const titleLineTwoX = useTransform(scrollYProgress, [0, isAboutProfile ? .22 : .12, isAboutProfile ? .46 : .3], ["0vw", "0vw", isAboutProfile ? "14vw" : "0vw"]);
  const titleLineThreeX = useTransform(scrollYProgress, [0, isAboutProfile ? .22 : .12, isAboutProfile ? .46 : .3], ["0vw", "0vw", isAboutProfile ? "-11vw" : "0vw"]);
  const titleLineTwoY = useTransform(scrollYProgress, [0, isAboutProfile ? .22 : .12, isAboutProfile ? .46 : .3], ["0vh", "0vh", isAboutProfile ? "3vh" : "0vh"]);
  const titleLineThreeY = useTransform(scrollYProgress, [0, isAboutProfile ? .22 : .12, isAboutProfile ? .46 : .3], ["0vh", "0vh", isAboutProfile ? "-2vh" : "0vh"]);
  const [intro, setIntro] = useState(false); const [scrolled, setScrolled] = useState(false); const [active, setActive] = useState<number | null>(null);

  useEffect(() => { if (reduced) return; try { if (!sessionStorage.getItem("3cuartos-intro-seen")) { sessionStorage.setItem("3cuartos-intro-seen", "1"); const start = window.setTimeout(() => setIntro(true), 0); const end = window.setTimeout(() => setIntro(false), 600); return () => { window.clearTimeout(start); window.clearTimeout(end); }; } } catch { /* storage unavailable */ } }, [reduced]);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > window.innerHeight * .72); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  const disciplines = services.slice(0, 3);
  return <>
    <div className={`${styles.scene} ${isAboutProfile ? styles.aboutScene : ""} ${scrolled ? styles.scrolled : ""}`}>
      <motion.div className={styles.intro} aria-hidden="true" initial={{ opacity: 0 }} animate={{ opacity: intro ? 1 : 0, pointerEvents: intro ? "auto" : "none" }} transition={{ duration: reduced ? 0 : .2 }}><BrandLogo tone="light" /><span /></motion.div>
      <section className={styles.hero} aria-labelledby="home-hero-title"><motion.div className={styles.heroCopy} style={reduced ? undefined : { x: heroExitX, y: heroExitY, opacity: heroOpacity, scale: heroScale }} initial={reduced ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: intro ? .6 : 0, duration: reduced ? .01 : .55 }}><p className={styles.eyebrow}>Estrategia, creatividad y tecnología</p><h1 id="home-hero-title"><motion.span style={reduced || !isAboutProfile ? undefined : { x: titleLineOneX }}>Todo conecta</motion.span><motion.span style={reduced || !isAboutProfile ? undefined : { x: titleLineTwoX, y: titleLineTwoY }}>cuando existe</motion.span><motion.span style={reduced || !isAboutProfile ? undefined : { x: titleLineThreeX, y: titleLineThreeY }}>una estrategia.</motion.span></h1><p className={styles.copy}>Marca, producto y comunicación trabajando como un solo sistema.</p><div><Button href={ctaUrl}>{ctaLabel}</Button><Button href="/servicios" variant="secondary">Explorar servicios</Button></div></motion.div>
        <motion.div className={styles.orbital} style={reduced ? undefined : { opacity: heroOpacity, scale: orbitalScale }}><svg className={styles.orbitSvg} viewBox="0 0 520 520" role="presentation" aria-hidden="true"><motion.circle className={`${styles.orbitArc} ${active === 0 ? styles.active : ""}`} cx="260" cy="260" r="188" pathLength="1" strokeDasharray=".26 .74" transform="rotate(-92 260 260)" initial={{ pathLength: reduced ? 1 : 0 }} animate={{ pathLength: 1 }} transition={{ duration: reduced ? 0 : .8, delay: .45 }} /><motion.circle className={`${styles.orbitArc} ${active === 1 ? styles.active : ""}`} cx="260" cy="260" r="188" pathLength="1" strokeDasharray=".26 .74" transform="rotate(28 260 260)" initial={{ pathLength: reduced ? 1 : 0 }} animate={{ pathLength: 1 }} transition={{ duration: reduced ? 0 : .8, delay: .58 }} /><motion.circle className={`${styles.orbitArc} ${active === 2 ? styles.active : ""}`} cx="260" cy="260" r="188" strokeDasharray=".26 .74" transform="rotate(148 260 260)" initial={{ pathLength: reduced ? 1 : 0 }} animate={{ pathLength: 1 }} transition={{ duration: reduced ? 0 : .8, delay: .71 }} />{disciplineDetails.map((detail, index) => <g key={`core-${index}`} className={`${styles.coreConnection} ${active === index ? styles.active : ""}`}>{index === 0 && <path d="M109 137 L214 227 M109 137 L306 227" />}{index === 1 && <path d="M412 137 L214 227 M412 137 L260 289" />}{index === 2 && <path d="M260 448 L214 227 M260 448 L306 227 M260 448 L260 289" />}</g>)}{disciplineDetails.map((detail, index) => <g key={index} className={`${styles.microConnections} ${active === index ? styles.active : ""}`}>{index === 0 && <path d="M109 137 L53 92 M109 137 L43 148 M109 137 L84 201" />}{index === 1 && <path d="M412 137 L465 93 M412 137 L479 146 M412 137 L440 202" />}{index === 2 && <path d="M260 448 L206 478 M260 448 L260 505 M260 448 L314 478" />}</g>)}<circle className={styles.decorNode} cx="84" cy="116" r="3" /><circle className={styles.decorNode} cx="438" cy="112" r="3" /><circle className={styles.decorNode} cx="260" cy="476" r="3" /></svg><div className={styles.coreCluster}>{["Estrategia", "Creatividad", "Tecnología"].map((name, index) => { const isCoreActive = active !== null && (index === 0 || active === 2 || (active === 0 && index === 1) || (active === 1 && index === 2)); return <motion.span key={`${active ?? "initial"}-${name}`} className={`${styles.coreCircle} ${styles[`core${index + 1}`]} ${isCoreActive ? styles.active : ""}`} animate={reduced || active === null || index !== 0 ? { scale: 1 } : { scale: [1, 1.035, 1] }} transition={{ duration: reduced ? 0 : .42, ease: "easeOut" }}>{name}</motion.span>; })}</div>{disciplines.map((service, index) => <span key={service.id} aria-hidden="true" className={`${styles.orbitNode} ${styles[`orbitNode${index + 1}`]} ${active === index ? styles.active : ""}`} />)}</motion.div>
        <motion.div className={styles.modules} style={reduced ? undefined : { y: modulesY, opacity: heroOpacity }} aria-label="Disciplinas conectadas">{disciplines.map((service, index) => { const detail = disciplineDetails[index]; const isActive = active === index; return <motion.article key={service.id} className={`${styles.moduleWrap} ${styles[`module${index + 1}`]} ${isActive ? styles.active : ""}`} initial={reduced ? false : { opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: intro ? .75 + index * .1 : .15 + index * .1, duration: reduced ? .01 : .4 }} onMouseEnter={() => setActive(index)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(index)} onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setActive(null); }}><button type="button" className={styles.moduleTrigger} aria-expanded={isActive} aria-controls={`service-capabilities-${index}`} onClick={() => setActive(isActive ? null : index)}><span>0{index + 1}</span><strong>{service.name}</strong></button><ul id={`service-capabilities-${index}`} className={styles.capabilityList}>{detail.capabilities.map((capability) => <li key={capability}>{capability}</li>)}</ul><Link className={styles.moduleLink} href={`/servicios/${service.slug}`}>Ver servicio <span className={styles.srOnly}>{service.name}</span> →</Link></motion.article>; })}</motion.div><span className={styles.sceneNote}>Contenido provisional — cliente</span><span className={styles.scrollHint} aria-hidden="true">Scroll para explorar ↓</span>
      </section>
    </div>
    {!heroOnly && <>
      <ProblemsSection />
      <HomeSystemScene />
      {showProjects && <section className={styles.projects} aria-labelledby="projects-title"><p className={styles.eyebrow}>Proyectos donde todo conecta</p><ScrollSplitHeading id="projects-title" className={styles.projectsTitle}>Proyectos donde estrategia, diseño y tecnología se encuentran.</ScrollSplitHeading><p className={styles.projectsIntro}>Selección provisional de proyectos. Contenido sujeto a aprobación.</p><div className={styles.projectGrid}>{projects.map((project, index) => <article className={styles[project.className]} key={project.name}><div className={styles.projectMedia}><Image src={project.image} alt={project.alt} fill sizes="(max-width: 767px) 100vw, (max-width: 1199px) 42vw, 33vw" priority={index === 0} /><span className={styles.projectProvisional}>Imagen provisional</span></div><div><span className={styles.projectNumber}>0{index + 1}</span><h3>{project.name}</h3><p>{project.category}</p><Link href="/casos-de-exito">Ver proyecto →</Link></div></article>)}</div><span className={styles.projectsNote}>Imágenes originales pendientes de autorización del cliente.</span></section>}
    </>}
  </>;
}
