"use client";
import Link from "next/link";
import Image from "next/image";
import { useEffect, useRef, useState } from "react";
import { motion, useReducedMotion, useScroll, useTransform } from "framer-motion";
import { Button } from "@/components/ui/button";
import type { Service } from "@/types/wordpress";
import styles from "./immersive-home.module.css";

const allLinks = [{ label: "Inicio", href: "/" }, { label: "Servicios", href: "/servicios" }, { label: "Casos de éxito", href: "/casos-de-exito" }, { label: "Proceso", href: "/proceso" }, { label: "Nosotros", href: "/nosotros" }, { label: "Recursos", href: "/recursos" }, { label: "Contacto", href: "/contacto" }];
const visibleLinks = allLinks.slice(1, 3);
const disciplineDetails = [
  { capabilities: ["Identidad", "Concepto", "Comunicación"] },
  { capabilities: ["UX/UI", "Desarrollo", "Automatización"] },
  { capabilities: ["Contenido", "Campañas", "Analítica"] },
];
const projects = [{ name: "Amazonas Fit", category: "Branding e identidad", className: "projectBrand", image: "/images/projects/amazonas-fit-provisional.png", alt: "Amazonas Fit — imagen provisional" }, { name: "Natuo", category: "E-commerce y marca", className: "projectProduct", image: "/images/projects/natuo-provisional.png", alt: "Natuo — imagen provisional" }, { name: "Anonymask Studio", category: "Experiencia digital", className: "projectDigital", image: "/images/projects/anonymask-studio-provisional.png", alt: "Anonymask Studio — imagen provisional" }];

export function ImmersiveHome({ services, ctaLabel, ctaUrl, showProjects = true }: { services: Service[]; ctaLabel: string; ctaUrl: string; showProjects?: boolean }) {
  const reduced = useReducedMotion(); const { scrollYProgress } = useScroll(); const heroScale = useTransform(scrollYProgress, [0, .16], [1, reduced ? 1 : .94]);
  const [menu, setMenu] = useState(false); const [intro, setIntro] = useState(false); const [scrolled, setScrolled] = useState(false); const [pointer, setPointer] = useState({ x: 0, y: 0 }); const [active, setActive] = useState<number | null>(null);
  const trigger = useRef<HTMLButtonElement>(null); const first = useRef<HTMLAnchorElement>(null);
  useEffect(() => { if (reduced) return; try { if (!sessionStorage.getItem("3cuartos-intro-seen")) { sessionStorage.setItem("3cuartos-intro-seen", "1"); const start = window.setTimeout(() => setIntro(true), 0); const end = window.setTimeout(() => setIntro(false), 600); return () => { window.clearTimeout(start); window.clearTimeout(end); }; } } catch { /* storage unavailable */ } }, [reduced]);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > window.innerHeight * .72); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { if (menu) first.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setMenu(false); requestAnimationFrame(() => trigger.current?.focus()); } if (event.key === "Tab" && menu) { const focusables = Array.from(document.querySelectorAll<HTMLElement>("[data-fullscreen-menu] a, [data-fullscreen-menu] button")); if (focusables.length && (event.shiftKey ? document.activeElement === focusables[0] : document.activeElement === focusables.at(-1))) { event.preventDefault(); (event.shiftKey ? focusables.at(-1) : focusables[0])?.focus(); } } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [menu]);
  useEffect(() => { document.body.style.overflow = menu ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menu]);
  const disciplines = services.slice(0, 3);
  return <>
    <div className={`${styles.scene} ${scrolled ? styles.scrolled : ""}`} onPointerMove={(event) => { if (!reduced && event.pointerType === "mouse") setPointer({ x: (event.clientX / window.innerWidth - .5) * 6, y: (event.clientY / window.innerHeight - .5) * 6 }); }}>
      <motion.div className={styles.intro} aria-hidden="true" initial={{ opacity: 0 }} animate={{ opacity: intro ? 1 : 0, pointerEvents: intro ? "auto" : "none" }} transition={{ duration: reduced ? 0 : .2 }}><strong>3cuartos</strong><span /></motion.div>
      <header className={styles.header}><Link className={styles.brand} href="/" aria-label="3cuartos, inicio">3cuartos</Link><nav className={styles.desktopNav} aria-label="Navegación principal">{visibleLinks.map((link) => <Link key={link.href} href={link.href}>{link.label === "Casos de éxito" ? "Casos" : link.label}</Link>)}</nav><Button className={styles.headerCta} href={ctaUrl}>{ctaLabel}</Button><button ref={trigger} className={styles.menuButton} type="button" aria-expanded={menu} aria-controls="fullscreen-menu" aria-label={menu ? "Cerrar menú" : "Abrir menú"} onClick={() => setMenu((value) => !value)}>{menu ? "Cerrar" : "Menú"}</button></header>
      {menu && <div id="fullscreen-menu" data-fullscreen-menu className={styles.overlay} role="dialog" aria-modal="true" aria-labelledby="fullscreen-menu-title"><div><p className={styles.menuKicker} id="fullscreen-menu-title">Navegación</p>{allLinks.map((link, index) => <Link ref={index === 0 ? first : undefined} key={link.href} href={link.href} onClick={() => setMenu(false)}><span>0{index + 1}</span>{link.label}</Link>)}<Button href="/contacto">Cuéntanos tu proyecto</Button></div></div>}
      <section className={styles.hero} aria-labelledby="home-hero-title"><motion.div className={styles.heroCopy} style={{ x: pointer.x, y: pointer.y, scale: heroScale }} initial={reduced ? false : { opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: intro ? .6 : 0, duration: reduced ? .01 : .55 }}><p className={styles.eyebrow}>Estrategia, creatividad y tecnología</p><h1 id="home-hero-title"><span>Todo conecta</span><span>cuando existe</span><span>una estrategia.</span></h1><p className={styles.copy}>Marca, producto y comunicación trabajando como un solo sistema.</p><div><Button href={ctaUrl}>{ctaLabel}</Button><Button href="/servicios" variant="secondary">Explorar servicios</Button></div></motion.div>
        <div className={styles.orbital}><svg className={styles.orbitSvg} viewBox="0 0 520 520" role="presentation" aria-hidden="true"><circle className={`${styles.orbitArc} ${active === 0 ? styles.active : ""}`} cx="260" cy="260" r="188" strokeDasharray="248 933" transform="rotate(-92 260 260)" /><circle className={`${styles.orbitArc} ${active === 1 ? styles.active : ""}`} cx="260" cy="260" r="188" strokeDasharray="248 933" transform="rotate(28 260 260)" /><circle className={`${styles.orbitArc} ${active === 2 ? styles.active : ""}`} cx="260" cy="260" r="188" strokeDasharray="248 933" transform="rotate(148 260 260)" />{disciplineDetails.map((detail, index) => <g key={`core-${index}`} className={`${styles.coreConnection} ${active === index ? styles.active : ""}`}>{index === 0 && <path d="M109 137 L210 222 M109 137 L310 222" />}{index === 1 && <path d="M412 137 L210 222 M412 137 L260 299" />}{index === 2 && <path d="M260 448 L210 222 M260 448 L310 222 M260 448 L260 299" />}</g>)}{disciplineDetails.map((detail, index) => <g key={index} className={`${styles.microConnections} ${active === index ? styles.active : ""}`}>{index === 0 && <path d="M109 137 L53 92 M109 137 L43 148 M109 137 L84 201" />}{index === 1 && <path d="M412 137 L465 93 M412 137 L479 146 M412 137 L440 202" />}{index === 2 && <path d="M260 448 L206 478 M260 448 L260 505 M260 448 L314 478" />}</g>)}<circle className={styles.decorNode} cx="84" cy="116" r="3" /><circle className={styles.decorNode} cx="438" cy="112" r="3" /><circle className={styles.decorNode} cx="260" cy="476" r="3" /></svg><div className={styles.coreCluster}>{["Estrategia", "Creatividad", "Tecnología"].map((name, index) => { const isCoreActive = active !== null && (index === 0 || active === 2 || (active === 0 && index === 1) || (active === 1 && index === 2)); return <motion.span key={`${active ?? "initial"}-${name}`} className={`${styles.coreCircle} ${styles[`core${index + 1}`]} ${isCoreActive ? styles.active : ""}`} animate={reduced || active === null || index !== 0 ? { scale: 1 } : { scale: [1, 1.035, 1] }} transition={{ duration: reduced ? 0 : .42, ease: "easeOut" }}>{name}</motion.span>; })}</div><span className={`${styles.orbitLabel} ${styles.orbitLabel1}`}>01 · Diseño y Branding</span><span className={`${styles.orbitLabel} ${styles.orbitLabel2}`}>02 · Desarrollo Web</span><span className={`${styles.orbitLabel} ${styles.orbitLabel3}`}>03 · Marketing Digital</span>{disciplines.map((service, index) => <span key={service.id} aria-hidden="true" className={`${styles.orbitNode} ${styles[`orbitNode${index + 1}`]} ${active === index ? styles.active : ""}`} />)}</div><ul className={styles.mobileOrbitLabels} aria-label="Disciplinas de la órbita"><li>01 · Diseño y Branding</li><li>02 · Desarrollo Web</li><li>03 · Marketing Digital</li></ul>
        <div className={styles.modules} aria-label="Disciplinas conectadas">{disciplines.map((service, index) => { const detail = disciplineDetails[index]; const isActive = active === index; return <motion.article key={service.id} className={`${styles.moduleWrap} ${styles[`module${index + 1}`]} ${isActive ? styles.active : ""}`} initial={reduced ? false : { opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: intro ? .75 + index * .1 : .15 + index * .1, duration: reduced ? .01 : .4 }} onMouseEnter={() => setActive(index)} onMouseLeave={() => setActive(null)} onFocus={() => setActive(index)} onBlur={(event) => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setActive(null); }}><button type="button" className={styles.moduleTrigger} aria-expanded={isActive} aria-controls={`service-capabilities-${index}`} onClick={() => setActive(isActive ? null : index)}><span>0{index + 1}</span><strong>{service.name}</strong></button><ul id={`service-capabilities-${index}`} className={styles.capabilityList}>{detail.capabilities.map((capability) => <li key={capability}>{capability}</li>)}</ul><Link className={styles.moduleLink} href={`/servicios/${service.slug}`}>Ver servicio <span className={styles.srOnly}>{service.name}</span> →</Link></motion.article>; })}</div><span className={styles.sceneNote}>Contenido provisional — cliente</span><span className={styles.scrollHint} aria-hidden="true">Scroll para explorar ↓</span>
      </section>
    </div>
    <section className={styles.transition} aria-labelledby="transition-title"><div className={styles.transitionCopy}><p className={styles.eyebrow}>Un sistema, múltiples capacidades.</p><h2 id="transition-title">Tres disciplinas. Una misma dirección.</h2><p>Conectamos marca, producto y crecimiento para construir experiencias que funcionan como un solo sistema.</p><Link href="/servicios">Explorar nuestros servicios →</Link></div><svg className={styles.transitionGraphic} viewBox="0 0 360 240" aria-hidden="true"><path d="M20 30 C120 30 160 120 330 120 M20 120 C120 120 160 120 330 120 M20 210 C120 210 160 120 330 120" /><circle cx="20" cy="30" r="4" /><circle cx="20" cy="120" r="4" /><circle cx="20" cy="210" r="4" /><circle cx="330" cy="120" r="7" /></svg></section>
    {showProjects && <section className={styles.projects} aria-labelledby="projects-title"><p className={styles.eyebrow}>Proyectos donde todo conecta</p><h2 id="projects-title">Proyectos donde estrategia, diseño y tecnología se encuentran.</h2><p className={styles.projectsIntro}>Selección provisional de proyectos. Contenido sujeto a aprobación.</p><div className={styles.projectGrid}>{projects.map((project, index) => <article className={styles[project.className]} key={project.name}><div className={styles.projectMedia}><Image src={project.image} alt={project.alt} fill sizes="(max-width: 767px) 100vw, (max-width: 1199px) 42vw, 33vw" priority={index === 0} /><span className={styles.projectProvisional}>Imagen provisional</span></div><div><span className={styles.projectNumber}>0{index + 1}</span><h3>{project.name}</h3><p>{project.category}</p><Link href="/casos-de-exito">Ver proyecto →</Link></div></article>)}</div><span className={styles.projectsNote}>Imágenes originales pendientes de autorización del cliente.</span></section>}
  </>;
}
